Enhance the example syslogd script to restart on SIGHUP

diff --git a/syslogd b/syslogd
--- a/syslogd
+++ b/syslogd
@@ -1,33 +1,40 @@
 #!/bin/bash
 
-if [[ $* != "-" ]]; then
-  unset FDATASYNC LOGDIR PIDFILE
-  while getopts :d:p:s OPTION; do
-    case $OPTION in
-      d)
-        LOGDIR=$OPTARG
-        ;;
-      p)
-        PIDFILE=$OPTARG
-        ;;
-      s)
-        FDATASYNC=1
-        ;;
-    esac
-  done
-  export FDATASYNC LOGDIR PIDFILE
-  exec daemon syslog "$0" -
-fi
+FDATASYNC=0
+LOGDIR=/var/log
+PIDFILE=/run/syslogd.pid
+RESTART=0
 
-LOGDIR=${LOGDIR:-/var/log}
-PIDFILE=${PIDFILE:-/run/syslogd.pid}
+while getopts :d:p:s OPTION; do
+  case $OPTION in
+    d)
+      LOGDIR=$OPTARG
+      ;;
+    p)
+      PIDFILE=$OPTARG
+      ;;
+    s)
+      FDATASYNC=1
+      ;;
+  esac
+done
 
-exec 3>>"$PIDFILE"
-if ! flock -n 3 2>/dev/null; then
-  echo "Failed to lock /run/syslogd.pid; is syslogd already running?" >&2
+if [[ ${*:$OPTIND} != "-" ]]; then
+  if { exec 3>>"$PIDFILE" && flock -n 3; } 2>/dev/null; then
+    exec daemon syslog "$0" "${@:1:$((OPTIND - 1))}" -
+    rm -f "$PIDFILE"
+  else
+    echo "Failed to lock $PIDFILE; is ${0##*/} already running?" >&2
+  fi
   exit 1
 fi
+
+trap 'RESTART=0 && exit' SIGTERM
+trap 'RESTART=1 && exit' SIGHUP SIGINT SIGUSR1 SIGUSR2
+trap '(( RESTART )) && exec "$0" "$@" || rm -f "$PIDFILE"' EXIT
+
 echo $PPID >"$PIDFILE"
+exec 3>&-
 
 while read -r FACILITY LEVEL DATE TIME MESSAGE; do
   if (( LEVEL > 6 )); then
@@ -40,7 +47,5 @@ while read -r FACILITY LEVEL DATE TIME MESSAGE; do
 
   mkdir -m 0700 -p "$LOGDIR/$FACILITY"
   echo "$TIME $MESSAGE" >>"$LOGDIR/$FACILITY/$DATE"
-  [[ -n $FDATASYNC ]] && fdatasync "$LOGDIR/$FACILITY/$DATE"
+  (( FDATASYNC )) && fdatasync "$LOGDIR/$FACILITY/$DATE"
 done
-
-rm -f "$PIDFILE"
