Remove subprocess support from uevent
It is no harder to run uevent as a child of ueventd rather than as the
parent, and this allows both a simpler uevent.c and a more logical
process tree.

Take care to kill the child correctly when terminating, but we keep it
alive across a SIGHUP-triggered re-exec to avoid dropping uevents.

diff --git a/ueventd b/ueventd
--- a/ueventd
+++ b/ueventd
@@ -6,6 +6,17 @@ RESTART=0
 SYSFS=${SYSFS:-/sys}
 TRIGGER=0
 
+usage() {
+  cat >&2 <<EOF
+Usage: ${0##*/} [OPTIONS]
+Options:
+  -f CONFFILE   set the configuration file, /etc/ueventd.conf by default
+  -p PIDFILE    set the pidfile location, /run/ueventd.pid by default
+  -t            retrigger a uevent for each pre-existing device
+EOF
+  exit 64
+}
+
 while getopts :f:p:t OPTION; do
   case $OPTION in
     f)
@@ -17,8 +28,13 @@ while getopts :f:p:t OPTION; do
     t)
       TRIGGER=1
       ;;
+    *)
+      usage
+      ;;
   esac
 done
+
+(( OPTIND <= $# )) && usage
 
 add() { :; }
 change() { :; }
@@ -34,22 +50,24 @@ elif ! source "$CONFFILE"; then
   exit 1
 fi
 
-if [[ ${*:$OPTIND} != "-" ]]; then
-  if { exec 3>>"$PIDFILE" && flock -n 3; } 2>/dev/null; then
-    exec env -i PATH="$PATH" daemon uevent "$0" "${@:1:OPTIND - 1}" -
-    rm -f "$PIDFILE"
-  else
-    echo "Failed to lock $PIDFILE; is ${0##*/} already running?" >&2
-  fi
+if ! { exec 3>>"$PIDFILE" && flock -n 3; } 2>/dev/null; then
+  echo "Failed to lock $PIDFILE; is ${0##*/} already running?" >&2
   exit 1
 fi
 
-trap 'RESTART=0 && exit' SIGTERM
-trap 'RESTART=1 && exit' SIGHUP SIGINT SIGUSR1 SIGUSR2
-trap '(( RESTART )) && exec "$0" "$@" || rm -f "$PIDFILE"' EXIT
+if read -a STAT </proc/self/stat && (( $$ != STAT[5] )); then
+  exec daemon -- "$0" "$@"
+  rm -f "$PIDFILE"
+  exit 1
+fi
 
-echo $PPID >"$PIDFILE"
-exec 3>&-
+echo $$ >"$PIDFILE"
+trap 'trap - TERM && kill -TERM 0 && rm -f "$PIDFILE"' EXIT
+trap 'exec -- "$0" "$@"' HUP
+
+if [[ ! -p /dev/stdin ]]; then
+  exec < <(uevent 3>&-)
+fi
 
 if (( TRIGGER )); then
   find $SYSFS/{module,bus,devices} -name uevent -type f \
